[env:esp32-s3-devkitc-1]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- FORZAR RUTAS DE LIBRERÍAS ---
lib_ldf_mode = deep+
lib_archive = no

build_flags = 
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=2
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; Esta línea obliga a buscar Audio.h en su carpeta real:
    -I .pio/libdeps/esp32-s3-devkitc-1/ESP32-audioI2S/src
    ; Esta línea ayuda con el error de WiFi:
    -I .platformio/packages/framework-arduinoespressif32/libraries/WiFi/src

build_unflags = -std=gnu++11    

lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
    links2004/WebSockets @ ^2.4.1
    adafruit/Adafruit NeoPixel @ ^1.11.0
    https://github.com/schreibfaul1/ESP32-audioI2S.git

board_build.filesystem = littlefs